name: CI

on:
  push:
    branches: [ main, master ]

env:
  REGISTRY: "cr.selcloud.ru/balobas"
  IMAGE_NAME: "auth_service"
  CONTAINER_NAME: "auth_service-container"
  EXTERNAL_PORT: 50051
  CONTAINER_PORT: 50051

jobs:
  image-build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Registry
        run: docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} $REGISTRY

      - name: Build and Push service Docker Image
        run: |
          TAG_NAME=$(echo $GITHUB_SHA | head -c7)
          docker buildx create --use
          docker buildx build --no-cache --push --tag $REGISTRY/$IMAGE_NAME:$TAG_NAME -f Dockerfile ./
        
      - name: Build and Push migrator Docker Image
        run: |
          TAG_NAME=$(echo $GITHUB_SHA | head -c7)
          docker buildx create --use
          docker buildx build --no-cache --push --tag $REGISTRY/migrator:$TAG_NAME -f migration.Dockerfile ./

  deploy-image:
    runs-on: ubuntu-latest
    needs: image-build-and-push

    steps:
      - name: Deploy to Selectel Cloud via SSH action
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSHKEY }}
          envs: IMAGE_NAME,REGISTRY,GITHUB_SHA,CONTAINER_NAME,EXTERNAL_PORT,CONTAINER_PORT
          script: |
            # Set up variables
            TAG_NAME=$(echo $GITHUB_SHA | head -c7)
            
            # Login into Selectel Registry
            docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} $REGISTRY
            
            # Stop running container
            docker stop $CONTAINER_NAME
            
            # Remove old container
            docker rm $CONTAINER_NAME

            # Stop migrator if it work
            docker stop migrator

            #Remove old migrator container
            docker rm migrator

            # Run migrations
            docker run -d --name=migrator --network db_network --restart on-failure -t $REGISTRY/migrator:$TAG_NAME
            
            # Run a new container from a new image
            docker run -d --network db_network -p $EXTERNAL_PORT:$CONTAINER_PORT --name $CONTAINER_NAME -t $REGISTRY/$IMAGE_NAME:$TAG_NAME


